### ISSUE TITLE
input a list of items in not_recommend?

### ISSUE THREAD

**Issue by dfalbel** [dselivanov/reco#15]
First of all, thanks very much for this package!

In my use case, I have to check the stock and see which products are available for recommendations. So usually I will have a list of items that I can't recommend for all users - This list may be very large.

I'm creating a sparse matrix with a lot of columns full of ones, and this is very slow. Would it be possible to pass a vector of items for the `not_recommend` argument?

Thanks,
Daniel

**Comment by dselivanov** [comment]
It is definitely possible - need just to ignored those items/item embeddings. I will think about how to include this option because I also have such use case. I the meantime you can use `transform` method to get user embeddings. And then multiply user embeddings by item embeddings (components) without out of stock items. Hope it helps.
I'm traveling at the moment, will provide some code once I will arrive tomorrow.

**Comment by dfalbel** [comment]
thanks very much!! This works fine!

**Comment by dfalbel** [comment]
I used the following to create the predictions:

```
teste_embdeddings <- model$transform(treino_x[uids, ])
item_embeddings <- model$components[, -iids_not_recommend]
pred <- reco:::find_top_product(teste_embdeddings, item_embeddings, k = 10)
```

Do you think this is right?

**Comment by dselivanov** [comment]
Yes

28 дек. 2017 г. 23:24 пользователь "Daniel Falbel" <notifications@github.com>
написал:

**Comment by dselivanov** [comment]
please test if you will have a chance - `items_exclude` argument. Can be both integer or character - indices or ids.

**Comment by dfalbel** [comment]
thanks! I'll test as soon as possible.
